In [31]:
from transforms3d.euler import quat2euler
import math as m

In [32]:
def normalize_angle(angle):
    """ Normalize the angle to the range [-pi, pi]. """
    return m.atan2(m.sin(angle), m.cos(angle))

In [33]:
test = [-0.7993715405464172, -0.5975781679153442, 0.03904560208320618, 0.04879523441195488]


[-0.8063313961029053, 0.011068995110690594, 0.591343104839325, 0.004523830488324165]
roll, pitch, yaw = quat2euler(test) #(-0.005448548314084914, -0.6230168375148765, -0.01056768867977631) AKA neg pitch when tilting forward to go front to +X
print(f"(roll,pitch,yaw)={roll,pitch,yaw}")


(roll,pitch,yaw)=(1.2841322882542774, -0.004105963900254393, -0.12500297536901528)


# test on data

### Negative Pitch Tilt Forward

In [34]:
sim_negpitch_goforward = [0.9518511295318604, -0.004212579224258661, -0.3064756989479065, -0.005864466540515423]
roll, pitch, yaw = quat2euler(sim_negpitch_goforward) #(-0.005448548314084914, -0.6230168375148765, -0.01056768867977631) AKA neg pitch when tilting forward to go front to +X
print(f"(roll,pitch,yaw)={roll,pitch,yaw}")

(roll,pitch,yaw)=(-0.005448548314084914, -0.6230168375148765, -0.010567688679776425)


In [35]:
hardware_negpitch_goforward = [0.8088037967681885, 0.026748254895210266, -0.5844698548316956, 0.05929585173726082]
roll, pitch, yaw = quat2euler(hardware_negpitch_goforward) #(-0.005448548314084914, -0.6230168375148765, -0.01056768867977631) AKA neg pitch when tilting forward to go front to +X
print(f"(roll,pitch,yaw)={roll,pitch,yaw}")

(roll,pitch,yaw)=(-0.0824016804329776, -1.2488296737922981, 0.20575859351363496)


### Positive Roll Tilt CW to +Y

In [36]:
sim_posroll_goright = [0.9685525298118591, 0.24774451553821564, -0.022614458575844765, -0.004153035115450621] #(0.5012406346841017, -0.04176093567396901, -0.019268071582676516) AKA pos roll when tilting CW from the back to go right to +Y
roll, pitch, yaw = quat2euler(sim_posroll_goright) #(-0.005448548314084914, -0.6230168375148765, -0.01056768867977631) AKA neg pitch when tilting forward to go front to +X
print(f"(roll,pitch,yaw)={roll,pitch,yaw}")

(roll,pitch,yaw)=(0.5012406346841017, -0.04176093567396901, -0.019268071582676478)


In [37]:
hardware_posroll_goright = [0.8066073656082153, 0.5910258293151855, -0.008194857276976109, -0.0024253912270069122]
roll, pitch, yaw = quat2euler(hardware_posroll_goright) #(-0.005448548314084914, -0.6230168375148765, -0.01056768867977631) AKA neg pitch when tilting forward to go front to +X
print(f"(roll,pitch,yaw)={roll,pitch,yaw}")

(roll,pitch,yaw)=(1.2647838377388503, -0.010353311601660782, -0.013600569530322343)


### Negative Yaw Rotate CCW About Z
REMEMBER: POSITIVE Z IS POINTING DOWN SO FROM THE TOP IT LOOKS CW BUT ITS ACTUALLY CCW

In [38]:
hardware_posyaw_goCCW = [0.7167863249778748, 0.0040621510706841946, 0.0057961419224739075, 0.6972570419311523]
roll, pitch, yaw = quat2euler(hardware_posyaw_goCCW) #(-0.005448548314084914, -0.6230168375148765, -0.01056768867977631) AKA neg pitch when tilting forward to go front to +X
print(f"(roll,pitch,yaw)={roll,pitch,yaw}")

(roll,pitch,yaw)=(0.013906685494729855, 0.0026444664358176084, 1.5431945698611313)


## New Data for Confirmation

In [39]:
q = [0.8040963411331177, 0.5921547412872314, -0.03682420775294304, -0.03776012733578682]
roll, pitch, yaw = quat2euler(q)
print(f"(roll,pitch,yaw)={roll,pitch,yaw}")


(roll,pitch,yaw)=(1.2702682947479076, -0.01450125261433671, -0.10453808718658118)


In [40]:
import math
def euler_from_quaternion(w, x, y, z):
        """
        Convert a quaternion into euler angles (roll, pitch, yaw)
        roll is rotation around x in radians (counterclockwise)
        pitch is rotation around y in radians (counterclockwise)
        yaw is rotation around z in radians (counterclockwise)
        """
        t0 = +2.0 * (w * x + y * z)
        t1 = +1.0 - 2.0 * (x * x + y * y)
        roll_x = math.atan2(t0, t1)
     
        t2 = +2.0 * (w * y - z * x)
        t2 = +1.0 if t2 > +1.0 else t2
        t2 = -1.0 if t2 < -1.0 else t2
        pitch_y = math.asin(t2)
     
        t3 = +2.0 * (w * z + x * y)
        t4 = +1.0 - 2.0 * (y * y + z * z)
        yaw_z = math.atan2(t3, t4)
     
        return roll_x, pitch_y, yaw_z # in radians

In [41]:
q = [0.8040963411331177, 0.5921547412872314, -0.03682420775294304, -0.03776012733578682]

In [42]:
euler_from_quaternion(*q)

(1.270268307114649, -0.014501252802078183, -0.1045380885375744)

In [43]:
from scipy.spatial.transform import Rotation as R
import numpy as np


In [44]:

# Example quaternion (w, x, y, z)
quat  = [1.0, 0., 0., 0.]
# Convert to (x, y, z, w) format
quat_xyzw = quat[1:] + [quat[0]]

print(f"{quat_xyzw = }")

# Convert to rotation matrix
rotation_matrix = R.from_quat(quat_xyzw).as_matrix()

print(rotation_matrix)


quat_xyzw = [0.0, 0.0, 0.0, 1.0]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
e1 = np.array([[1.],
       [0.],
       [0.]])
b2 = np.array([[ 0.        ],
       [-0.99999702],
       [-0.00244167]])
a3 = np.array([[ 0],
       [ 0],
       [-1]])


In [46]:
# Define matrices A and B
A = np.hstack((e1, b2, a3))
B = rotation_matrix

# Define known values in x and y
x_known = np.array([0.0921])  # x3 = 5
y_known = np.array([0.03324, .03242])  # y1 = 4, y2 = 2

# Split A into parts affecting unknowns (A1) and knowns (A2)
A1 = A[:, :2]  # First two columns (unknown x1, x2)
A2 = A[:, 2:]  # Last column (known x3)

# Split B into parts affecting unknowns (B1) and knowns (B2)
B1 = B[:, 2:]  # Last column (unknown y3)
B2 = B[:, :2]  # First two columns (known y1, y2)

# Compute right-hand side
rhs = (B2 @ y_known) - (A2 @ x_known)  # Move known values to RHS

# Solve system for [x1, x2, y3]
M = np.hstack((A1, -B1))  # Construct coefficient matrix
unknowns = np.linalg.solve(M, rhs)  # Solve for unknowns

# Extract solutions
x1, x2, y3 = unknowns

# Display results
x1, x2, y3


(0.03324, -0.0324200966118879, -0.09202084082270565)

In [47]:
x_known.shape

(1,)

In [48]:
y_known.shape

(2,)

In [49]:
def euler_to_rotation_matrix(roll, pitch, yaw):
    """
    Converts Euler angles (roll, pitch, yaw) to a rotation matrix.
    
    Parameters:
        roll (float): Rotation around x-axis (in radians)
        pitch (float): Rotation around y-axis (in radians)
        yaw (float): Rotation around z-axis (in radians)

    Returns:
        numpy.ndarray: 3x3 rotation matrix
    """
    # Compute cosines and sines
    c_roll, s_roll = np.cos(roll), np.sin(roll)
    c_pitch, s_pitch = np.cos(pitch), np.sin(pitch)
    c_yaw, s_yaw = np.cos(yaw), np.sin(yaw)

    # Rotation matrices
    R_x = np.array([[1, 0, 0],
                    [0, c_roll, -s_roll],
                    [0, s_roll, c_roll]])

    R_y = np.array([[c_pitch, 0, s_pitch],
                    [0, 1, 0],
                    [-s_pitch, 0, c_pitch]])

    R_z = np.array([[c_yaw, -s_yaw, 0],
                    [s_yaw, c_yaw, 0],
                    [0, 0, 1]])

    # Final rotation matrix
    R = R_z @ R_y @ R_x
    return R

# Example usage:
roll, pitch, yaw = np.radians([30, 45, 60])  # Convert degrees to radians
rotation_matrix = euler_to_rotation_matrix(roll, pitch, yaw)
print(rotation_matrix)


[[ 0.35355339 -0.5732233   0.73919892]
 [ 0.61237244  0.73919892  0.28033009]
 [-0.70710678  0.35355339  0.61237244]]


In [50]:
eulers = (-0.007815223444964419, 0.004138315266847287, -0.018880082226702757)
quats = R.from_euler('xyz', eulers).as_quat()
print(f"{quats = }")

quats = array([-0.00388789,  0.00210594, -0.00943172,  0.99994574])
